---
- name: Conf webserver with nginx
  hosts: test
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        update_cache: true

    - name: Copy nginx cfg file
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: 0644

    - name: Enable cfg
      ansible.builtin.file:
        dest: /etc/nginx/sites-enabled/default
        src: /etc/nginx/sites-available/default
        state: link

    - name: Copy index.html
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0644

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
